Convert associated abspaths
SETI/rms-pdsfile pull request #17
Opened 2023-12-09 06:30 UTC by juzen2003

Changes made:
- Add rules for `ASSOCIATIONS` (`associations_to_bundles`, `associations_to_previews`, `associations_to_metadata`, `associations_to_documents`)
- Add tests for those rules except `associations_to_metadata` since we need to create the index files for them
- Update r`un_tests_coverages.sh` to run only pds3 tests when use_shelves_only is True because we don't have shelves for pds4 yet
- Replace all `holdings` with `cls.PDS_HOLDINGS` in `pdsfile.py`
- Create previews, documents, calibrated, metadata directories at the same level as bundles in Dropbox
    - Please review the structure of reviews, documents, calibrated, metadata directories and see if they make sense.

Known issues:
- For uranus under documents directory, it's currently empty. No ideas what files we should put here.
- For metadata directories, we need to create new index files, will have to work on the script under `validation`directory.

2024-02-16 23:23 UTC, juzen2003 commented
- Merge current main
- Add test cases for `associations_to_metadata` rules for `uranus_occs_earthbased` (`test_associated_abspaths`)
- Create two index files for `data/rings` and `data/global`:
    - `Pds4FileTest/pds4-holdings/metadata/uranus_occs_earthbased/uranus_occ_u0_kao_91cm/occ_rings.csv`
    - `Pds4FileTest/pds4-holdings/metadata/uranus_occs_earthbased/uranus_occ_u0_kao_91cm/occ_global.csv`

2024-02-20 21:26 UTC, pds-admin commented on run_tests_coverage.sh
> +    # Only run with use shelves for pds3, we don't have shelves for pds4 for now
This file has gotten really complicated. How about just having four separate test lines with the appropriate arguments and skipping all the arrays and loops and conditionals?

2024-02-20 21:27 UTC, rfrenchseti commented on run_tests_coverage.sh
> +    # Only run with use shelves for pds3, we don't have shelves for pds4 for now
This file has gotten really complicated. How about just having four separate test lines with the appropriate arguments and skipping all the arrays and loops and conditionals?

2024-02-20 21:53 UTC, rfrenchseti requested changes
I did a basic review of the files excluding ISS and VIMS, which I don't know anything about.

2024-02-20 21:53 UTC, rfrenchseti commented on pdsfile/pdsfile.py
> +            raise ValueError('"{}" directory not found in: '.format(cls.PDS_HOLDINGS)
Let's get rid of uses of `format` and switch to f-strings everywhere.

2024-02-20 21:53 UTC, rfrenchseti commented on pdsfile/pds4file/rules/uranus_occs_earthbased.py
> +        [r'bundles/uranus_occs_earthbased',
Why is the same thing in the list three times?

2024-02-20 21:53 UTC, rfrenchseti commented on pdsfile/pds4file/rules/uranus_occs_earthbased.py
> +        [r'previews/\1_full.png',
Can leave this but I'll just point out we don't have any preview images yet.

2024-02-20 21:53 UTC, rfrenchseti commented on pdsfile/pds4file/rules/uranus_occs_earthbased.py
> +    (r'.*/(uranus_occs_earthbased)/(uranus_occ_u.*)/(data|browse)(.*|_[a-z]*])/(rings|global)/(.*)\.[a-z]{3}', 0,
There will only be one metadata directory for the whole bundleset, not a subdirectory per bundle.

2024-02-24 00:41 UTC, juzen2003 commented
Update based on comments:
- Add test case for metadata associated abspaths to test on the pdsfile instance of the entire bundle. Commented out test cases that test on the pdsfile instance of a data file (These will work when we add index shelf files later on)
- Replace `.format` with f string interpolation in `pdsfile.py`
- Simplify `run_tests_coverage.sh`

2024-03-05 02:37 UTC, mace-space approved these changes
Looks good

2024-03-12 18:20 UTC, rfrenchseti approved these changes

2024-03-12 19:06 UTC, merged