Update the test framework
SETI/rms-pdsfile pull request #52
Opened 2024-08-27 17:24 UTC by juzen2003

Update the test framework so that it's easier to write and update tests. 
- Fixed #40
  - Modfiy the test framework to either compare results with golden copies or update the golden copies with the latest output (currently opus products and associated abspaths has been updated to use the new test framework). Here are the example commands:
    - Update all golden copies using '--update' param
        ```
        pytest pdsfile/pds3file/rules/* --update
        pytest pdsfile/pds4file/rules/* --update
        ```
        or
        `./run_tests_coverage.sh --update`
    - Update all golden copies of VG_28xx
        `pytest pdsfile/pds3file/rules/VG_28xx.py --update`
    - Update golden copy of VG_28xx opus products test  
        `pytest pdsfile/pds3file/rules/VG_28xx.py::test_opus_products --update`
- Fixed #41
  - Create a standalone script to display more readable opus products output:
    - Display a table with opus type in the first column and its corresponding pdsfile list in the second column
    `python3 utility/show_opus_products.py --abspath='/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-OPUS/pdsdata/holdings/volumes/COCIRS_5xxx/COCIRS_5408/DATA/POIDATA/POI0408010000_FP1.LBL'`

    - Show opus products output with customized format (with '-r' param):
    `python3 utility/show_opus_products.py --abspath='/Users/yu-jenchang/Dropbox (SETI Institute)/Shared-OPUS/pdsdata/holdings/volumes/COCIRS_5xxx/COCIRS_5408/DATA/POIDATA/POI0408010000_FP1.LBL' -r`
- Fixed #42
  - Create these top level functions in PdsFile class to set variables in Pds3File & Pds4File subclasses
  ```
  use_shelves_only
  require_shelves
  set_logger
  set_easylogger
  ```
- Status of other bugs:
    - #37: Clean up tests in the rules. Now each volset will run the same opus products and associated abspaths tests ( under `pdsfile/pdsfile_test_helper.py`).   `test_opus_id_to_primary_logical_path` (mostly added by Mark) is run in each volset as well, but the function is specific to each volset. There is `test_opus_products_count` function run in three volset only (added by Mark), not sure why we need this since we already have opus products tests. Maybe we should remove them? 
    - #5, #6, #7: work in progress

2024-08-29 22:39 UTC, juzen2003 commented
8/29/24 update: (Top comment is updated)
- Change all golden copies from `.py` to `.txt` and store contents using `pprint` so that they can be easily diff to compare results.
- Add and update more options for `show_opus_products.py`, example commands are added in the top comments (issue 41 area).

2024-09-03 19:55 UTC, rfrenchseti requested changes
- The automated tests aren't running because the branch isn't up-to-date with `main`
- When I run the tests myself against either the OPUS Dropbox or the real holdings I get a bunch of failures.

2024-09-03 19:55 UTC, rfrenchseti commented on COCIRS_xxxx/associated_abspaths/volumes_POI0408010000_FP1.py
> +['volumes/COCIRS_5xxx/COCIRS_5408/DATA/APODSPEC/SPEC0408010000_FP1.DAT', 'volumes/COCIRS_5xxx/COCIRS_5408/DATA/APODSPEC/SPEC0408010000_FP1.LBL', 'volumes/COCIRS_5xxx/COCIRS_5408/DATA/ISPMDATA/ISPM040
Shouldn't this be pretty-printed?

2024-09-03 19:55 UTC, rfrenchseti commented on COCIRS_xxxx/opus_products/000IA_PRESOI001____RI____699_F4_038P.py
> +{('Cassini CIRS', 10, 'cocirs_cube', 'Spectral Image Cube', True): ['volumes/COCIRS_0xxx/COCIRS_0406/DATA/CUBE/POINT_PERSPECTIVE/000IA_PRESOI001____RI____699_F4_038P.tar.gz', 'volumes/COCIRS_0xxx/COC
Shouldn't this be pretty-printed?

2024-09-03 19:55 UTC, rfrenchseti commented on pdsfile/pds4file/rules/uranus_occs_earthbased.py
> +         r'bundles/\1/uranus_occ_support/document/user_guide/*.txt',
There are no `*.txt` files there. `*.py` was correct. The Python programs are part of the documentation.

2024-09-03 19:55 UTC, rfrenchseti commented on pdsfile/pds4file/rules/uranus_occs_earthbased.py
> +        ('bundles/uranus_occs_earthbased/uranus_occ_u0_kao_91cm/data/atmosphere/ u0_kao_91cm_734nm_counts-v-time_atmos_egress.xml',
Is there supposed to be a space in the filename?

2024-09-03 19:55 UTC, rfrenchseti commented on pdsfile/pdsfile.py
> +    def use_shelves_only(cls, pds3_status=True, pds4_status=True):
For this and `require_shelves` the point is to set both subclasses to the same value. If there are two parameters, we might as well just call the two subclass functions directly.

2024-09-03 19:55 UTC, rfrenchseti commented on pdsfile/pdsfile.py
> +             child_class.set_logger(pdslogger.EasyLogger())
These should probably be set to the set EasyLogger.

2024-09-03 20:03 UTC, rfrenchseti requested changes
For `show_opus_products`:
- Perhaps we don't need the separate abspath and logical path command line options? Just try one and then the other and use whichever doesn't throw an error.
- At the same time, it would be nice to be able to specify more than one path on the command line and just have it cycle through them printing the opus products for each.
- Probably no point in printing the big "OPUS PRODUCTS OUTPUT" header since it's obvious they are opus products.

2024-09-04 23:03 UTC, juzen2003 commented
9/4/24 update: (Top comment is updated)
- Update based on github comments
- Fixed issue 5 and 7
- Update the status of issue 6

2024-09-05 21:31 UTC, rfrenchseti approved these changes

2024-09-05 21:31 UTC, merged